### ISSUE TITLE
インデント等の修正

### ISSUE THREAD

**Issue by reika0717** [reika0717/graduation-project#2]
インデントや不要な行の削除等、コードを見やすく修正します。

**Comment by sundaycrafts** [comment]
https://dirtymarkup.com/ が便利ですよー。
node.jsのモジュールで、git commit時に勝手にフォーマットしてくれるユーティリティがあり、おそらくsass / html でも使えるので、後々はそれで対応でもいいかもしれません。

**Comment by reika0717** [comment]
有難うございます！使ってみます。
node.js色々できますね。
そしてlabel,Milestoneの追加有難うございます！
慣れるためにつけていくようにします！
