### ISSUE TITLE
head内のjavascriptを別ファイルに

### ISSUE THREAD

**Issue by reika0717** [reika0717/graduation-project#3]
現在header内に書いてあるjavascriptを別ファイルにし、linkで呼び出す。

**Comment by sundaycrafts** [comment]
`<script>` は基本的に、初期表示をできるだけ早くするため、以下のようにbodyタグの閉じタグの直前で読み込むのが慣習です。

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  <!-- ここに色々なコンテンツ -->
  <script src="./assets/script/script.js"></script>
</body>
</html>
```

**Comment by reika0717** [comment]
なるほど、、！
複雑な動きは順番後にすることで読み込ませやすくなるんですね。
別ファイルでなく、上記例参考に修正します！
有難うございます！

**Comment by sundaycrafts** [comment]
> 別ファイルでなく、上記例参考に修正します！

別ファイルは別ファイルですよ！headタグの中でなく、bodyタグの一番最後に読み込むようにするだけです！！

とりあえずhtmlに書いてあるjsを全部1つのjsファイルに纏めてもらえればダイジョブですー！

**Comment by reika0717** [comment]
！
なるほど！
linkをbodyタグの閉じタグの前に書くってことですね。。
よく見たらいただいたソースそうなってますね、、失礼しました。
