### ISSUE TITLE
CSS順序の整理

### ISSUE THREAD

**Issue by reika0717** [reika0717/graduation-project#4]
順番がばらばらになっているので整理。
（いっそのことSASSでコーディングしてしまいたい。）

**Comment by sundaycrafts** [comment]
scssならcssとの後方互換性があるので、すぐに1つにまとめることができると思います！
まず最初に1つにまとめるところからやってみてはいかがでしょうか？？

**Comment by reika0717** [comment]
やってみます！

**Comment by reika0717** [comment]
ジェシーさんすみません！
今このissue対応中なのですが、１つにまとめるというのは複数あるcssを一つにまとめるという意味でしょうか？？

**Comment by reika0717** [comment]
とりあえずSCSSでコーディングしなおしてます！

**Comment by sundaycrafts** [comment]
> 今このissue対応中なのですが、１つにまとめるというのは複数あるcssを一つにまとめるという意味でしょうか？？

そうです！scss使うと1つのcssにまとめられるので基本的にまとめてもらえると！
