### ISSUE TITLE
CSS不要な命令の削除

### ISSUE THREAD

**Issue by reika0717** [reika0717/graduation-project#5]
検証ツールで効いてない命令を調べ、削除する。

**Comment by sundaycrafts** [comment]
お手軽な検証ツールありますか？？自分も知らないので教えてほしいです！！
すぐできるなら問題ないですが、自分としてはレビューに支障ないので、こちら大変でしたら優先度下げて対応していただいても大丈夫です！

**Comment by reika0717** [comment]
chromeの検証ツールで効いてない命令取り消し線付きで出てくるのでそれ見て確認しようかと思っておりました！
ただこちら1つ1つやると時間かかると思うので一番最後にやります。
（text-alignとかz-indexとか命令が効かないことがコーディングしていてよくあったのでその原因だけでもわかればと思ってます！）
